# Generated by Django 2.2.1 on 2019-05-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190417_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='temps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temps_set', to='server.TempModel'),
        ),
    ]
